"use client";

import { useEffect, useState } from "react";
import {
  Brain,
  Wand2,
  Webhook,
  Gauge,
  ListOrdered,
  Compass,
  MessageSquareQuote,
  Sparkles,
  Copy,
  type LucideIcon,
} from "lucide-react";
import type { PlanRecipeRecord } from "@/lib/plan-recipe";

interface Props {
  projectRoot: string | null;
  planSlug: string | null;
  planContent: string;
  planTitle: string;
}

export function PlanRecipe({ projectRoot, planSlug, planContent, planTitle }: Props) {
  const [record, setRecord] = useState<PlanRecipeRecord | null>(null);
  const [stale, setStale] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!projectRoot || !planSlug) {
      setRecord(null);
      setStale(false);
      return;
    }
    fetch(`/api/recipe/${planSlug}?projectRoot=${encodeURIComponent(projectRoot)}`)
      .then((r) => r.json())
      .then((data) => {
        if (data?.error) throw new Error(data.error);
        setRecord(data.record);
        setStale(!!data.stale);
      })
      .catch((e) => setError(e.message ?? String(e)));
  }, [projectRoot, planSlug]);

  async function generate() {
    if (!projectRoot || !planSlug) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(
        `/api/recipe/${planSlug}?projectRoot=${encodeURIComponent(projectRoot)}`,
        { method: "POST" }
      );
      const data = await res.json();
      if (data?.error) throw new Error(data.error);
      setRecord(data.record);
      setStale(false);
    } catch (e: any) {
      setError(e.message ?? String(e));
    } finally {
      setLoading(false);
    }
  }

  async function copyRecipeAsPrompt() {
    if (!record) return;
    const r = record.recipe;
    const lines: string[] = [];
    lines.push(`# Approved plan: ${planTitle}`);
    lines.push("");
    lines.push("## Claude Code recipe (generated by Adeptly)");
    lines.push("");
    if (r.start_with_plan_mode) lines.push("**Start in Plan Mode.** Confirm the approach before any tool calls.");
    if (r.subagents.length) {
      lines.push("");
      lines.push("### Subagents to spawn");
      for (const s of r.subagents) lines.push(`- ${s.count} × ${s.type} — ${s.for}`);
    }
    if (r.skills.length) {
      lines.push("");
      lines.push("### Skills to invoke");
      for (const s of r.skills) lines.push(`- ${s.name} — ${s.when}`);
    }
    if (r.hooks_to_consider.length) {
      lines.push("");
      lines.push("### Hooks worth setting up");
      for (const h of r.hooks_to_consider) lines.push(`- ${h.type} — ${h.for}`);
    }
    lines.push("");
    lines.push(`**Expected turns:** ${r.expected_turns}`);
    lines.push(`**Estimated cost:** $${r.estimated_cost_usd.toFixed(2)} USD`);
    lines.push("");
    lines.push("### Execution order");
    for (const step of r.execution_order) lines.push(`- ${step}`);
    lines.push("");
    lines.push("### Rationale");
    lines.push(r.rationale);
    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push("## Plan");
    lines.push("");
    lines.push(planContent);
    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push(
      "Please execute this plan exactly as described, following the recipe above. If anything is unclear, ask before changing code. Use Plan Mode if the change is larger than a single edit."
    );
    try {
      await navigator.clipboard.writeText(lines.join("\n"));
      alert("Plan + recipe copied to clipboard.");
    } catch (e: any) {
      setError("Copy failed: " + (e.message ?? String(e)));
    }
  }

  if (!planSlug) return null;

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2 flex-wrap">
        <button
          onClick={generate}
          disabled={loading}
          className={`text-xs px-3 py-1.5 rounded text-white transition-all flex items-center gap-1.5 ${
            loading ? "recipe-generating" : "bg-accent-gradient"
          } disabled:opacity-60`}
        >
          <Sparkles size={14} strokeWidth={1.5} />
          {loading
            ? "Asking Claude…"
            : record
            ? stale
              ? "Regenerate (plan changed)"
              : "Regenerate recipe"
            : "Generate Claude Code recipe"}
        </button>
        {record && (
          <button
            onClick={copyRecipeAsPrompt}
            className="text-xs px-3 py-1.5 rounded bg-accent-gradient text-white flex items-center gap-1.5"
          >
            <Copy size={14} strokeWidth={1.5} />
            Copy plan + recipe as prompt
          </button>
        )}
        {record && (
          <span className="text-[10px] text-fg-secondary font-mono">
            {record.source === "claude-cli" ? "via claude --print" : "fallback (no Claude CLI)"} ·{" "}
            {new Date(record.generatedAt).toLocaleString()}
          </span>
        )}
        {stale && (
          <span className="chip chip-review !text-[10px] !px-1.5">
            stale — plan content has changed since this recipe was generated
          </span>
        )}
      </div>

      {error && (
        <div className="text-xs chip-changes p-2 rounded">
          {error}
        </div>
      )}

      {record?.error && (
        <div className="text-xs chip-review p-2 rounded">
          <div className="font-semibold">Notice</div>
          {record.error}
          {record.source === "fallback-keyword" && (
            <div className="mt-1">
              Make sure the <span className="font-mono">claude</span> CLI is installed and on PATH
              (try <span className="font-mono">claude --version</span> in a shell). Without it,
              Adeptly uses a generic fallback recipe.
            </div>
          )}
        </div>
      )}

      {!record && !loading && (
        <div className="border border-dashed border-border-strong rounded-md p-4 text-center space-y-2">
          <div className="flex justify-center">
            <Sparkles size={20} className="text-accent-1" strokeWidth={1.5} />
          </div>
          <div className="text-sm text-fg font-medium">No recipe yet</div>
          <div className="text-xs text-fg-secondary leading-relaxed max-w-md mx-auto">
            Click <strong className="text-fg">Generate Claude Code recipe</strong> above.
            Adeptly will ask Claude which subagents, skills, hooks, and execution order best
            fit <em>this specific plan</em>, plus an upfront cost estimate.
          </div>
          <div className="text-[10px] text-fg-tertiary pt-1">
            Uses your local <span className="font-mono">claude --print</span>. No API key.
          </div>
        </div>
      )}

      {record && (
        <div className="space-y-3">
          <RecipeBlock
            icon={MessageSquareQuote}
            title="Rationale"
            body={<p className="text-sm text-fg leading-relaxed">{record.recipe.rationale}</p>}
          />

          <RecipeBlock
            icon={Compass}
            title="Start"
            body={
              <p className="text-sm text-fg">
                {record.recipe.start_with_plan_mode
                  ? "Begin in Plan Mode — get the approach approved before any tool calls."
                  : "Plan Mode not required for this scope."}
              </p>
            }
          />

          <RecipeBlock
            icon={Brain}
            title={`Subagents (${record.recipe.subagents.length})`}
            body={
              record.recipe.subagents.length === 0 ? (
                <div className="text-xs text-fg-secondary italic">None needed for this plan.</div>
              ) : (
                <ul className="space-y-1.5">
                  {record.recipe.subagents.map((s, i) => (
                    <li key={i} className="text-sm flex items-baseline gap-2">
                      <span className="font-mono font-semibold text-accent-1 shrink-0">
                        {s.count} × {s.type}
                      </span>
                      <span className="text-fg">{s.for}</span>
                    </li>
                  ))}
                </ul>
              )
            }
          />

          <RecipeBlock
            icon={Wand2}
            title={`Skills (${record.recipe.skills.length})`}
            body={
              record.recipe.skills.length === 0 ? (
                <div className="text-xs text-fg-secondary italic">None recommended.</div>
              ) : (
                <ul className="space-y-1.5">
                  {record.recipe.skills.map((s, i) => (
                    <li key={i} className="text-sm flex items-baseline gap-2">
                      <span className="font-mono font-semibold text-accent-1 shrink-0">{s.name}</span>
                      <span className="text-fg">{s.when}</span>
                    </li>
                  ))}
                </ul>
              )
            }
          />

          <RecipeBlock
            icon={Webhook}
            title={`Hooks to consider (${record.recipe.hooks_to_consider.length})`}
            body={
              record.recipe.hooks_to_consider.length === 0 ? (
                <div className="text-xs text-fg-secondary italic">No hook needed for this plan.</div>
              ) : (
                <ul className="space-y-1.5">
                  {record.recipe.hooks_to_consider.map((h, i) => (
                    <li key={i} className="text-sm flex items-baseline gap-2">
                      <span className="font-mono font-semibold text-accent-1 shrink-0">{h.type}</span>
                      <span className="text-fg">{h.for}</span>
                    </li>
                  ))}
                </ul>
              )
            }
          />

          <RecipeBlock
            icon={Gauge}
            title="Estimates"
            body={
              <div className="text-sm grid grid-cols-2 gap-2">
                <div>
                  <div className="text-[10px] uppercase tracking-wide text-fg-secondary">
                    Expected turns
                  </div>
                  <div className="font-mono text-xl text-fg tracking-tight">{record.recipe.expected_turns}</div>
                </div>
                <div>
                  <div className="text-[10px] uppercase tracking-wide text-fg-secondary">
                    Estimated cost
                  </div>
                  <div className="font-mono text-xl tracking-tight bg-accent-gradient bg-clip-text text-transparent">
                    ${record.recipe.estimated_cost_usd.toFixed(2)}
                  </div>
                </div>
              </div>
            }
          />

          <RecipeBlock
            icon={ListOrdered}
            title={`Execution order (${record.recipe.execution_order.length} steps)`}
            body={
              <ol className="space-y-1 text-sm">
                {record.recipe.execution_order.map((step, i) => {
                  const cleaned = step.replace(/^\s*\d+[\.\)]\s*/, "");
                  return (
                    <li key={i} className="flex gap-2 text-fg">
                      <span className="font-mono text-accent-1 shrink-0 w-5">{i + 1}.</span>
                      <span>{cleaned}</span>
                    </li>
                  );
                })}
              </ol>
            }
          />
        </div>
      )}
    </div>
  );
}

function RecipeBlock({
  icon: Icon,
  title,
  body,
}: {
  icon: LucideIcon;
  title: string;
  body: React.ReactNode;
}) {
  return (
    <div className="border border-border-subtle rounded-md p-3 bg-elevated">
      <div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-fg-secondary mb-2">
        <Icon size={12} strokeWidth={1.5} className="text-accent-1" />
        {title}
      </div>
      {body}
    </div>
  );
}
